import { ProductAnalysisResponse } from '../../types/product';

interface ProductResultCardProps {
  result: ProductAnalysisResponse;
  isApproveDisabled: boolean;
  onApprove: () => void;
  onCancel: () => void;
}

function ProductResultCard({
  result,
  isApproveDisabled,
  onApprove,
  onCancel
}: ProductResultCardProps) {
  return (
    <div className="result-card">
      <div className="result-card-header">
        <h3>Analysis Result</h3>
        <p>Review the product details before approving the registration.</p>
      </div>

      <div className="result-grid">
        <div className="result-item full-width">
          <span className="label">Description</span>
          <p>
            {result.description ?? 'Description will be generated by AI soon.'}
          </p>
        </div>

        <div className="result-item full-width">
          <span className="label">Suggested Price</span>
          <p>
            {result.suggestedPrice != null
              ? `$${result.suggestedPrice.toFixed(2)}`
              : 'Suggested price will be available soon.'}
          </p>
        </div>
      </div>

      {isApproveDisabled && (
        <div className="alert-text">
          {result.message}
        </div>
      )}

      <div className="result-actions">
        <button
          type="button"
          className="secondary-button"
          onClick={onCancel}
        >
          Cancel
        </button>

        <button
          type="button"
          className="primary-button"
          onClick={onApprove}
          disabled={isApproveDisabled}
          aria-disabled={isApproveDisabled}
          title={
            isApproveDisabled
              ? 'Cannot approve a non-clothing item'
              : 'Approve registration'
          }
          style={
            isApproveDisabled
              ? { cursor: 'not-allowed', opacity: 0.5 }
              : undefined
          }
        >
          Approve Registration
        </button>
      </div>
    </div>
  );
}

export default ProductResultCard;