<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google_GenerativeAI" Version="3.6.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.9" />
    <PackageReference Include="OpenAI" Version="2.12.0" />
    <PackageReference Include="SkiaSharp" Version="4.150.0" />
	<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.150.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClothingStore.Application\ClothingStore.Application.csproj" />
  </ItemGroup>

</Project>
